// maki.config.js — developer's single config file
export default {
  width: 800, // game canvas width in px — editor canvas matches this
  height: 600, // game canvas height in px — editor canvas matches this
  maps: ["begin", "act_1", "act_2"],
  sprites: [
    {
      name: "player",
      file: "tiles_kenney/player.png",
      frameWidth: 16,
      frameHeight: 16,
      directions: {
        down: { start: 0, end: 0 },
        left: { start: 0, end: 0 },
        right: { start: 0, end: 0 },
        up: { start: 0, end: 0 },
      },
    },
    {
      name: "dad",
      file: "tiles_kenney/dad.png",
      frameWidth: 16,
      frameHeight: 16,
      directions: {
        down: { start: 0, end: 0 },
        left: { start: 0, end: 0 },
        right: { start: 0, end: 0 },
        up: { start: 0, end: 0 },
      },
    },
    {
      name: "sword1",
      file: "tiles_kenney/sword1.png",
      frameWidth: 16,
      frameHeight: 16,
      directions: {
        down: { start: 0, end: 0 },
        left: { start: 0, end: 0 },
        right: { start: 0, end: 0 },
        up: { start: 0, end: 0 },
      },
    },
    {
      name: "enemy",
      file: "tiles_kenney/enemy.png",
      frameWidth: 16,
      frameHeight: 16,
      directions: {
        down: { start: 0, end: 0 },
        left: { start: 0, end: 0 },
        right: { start: 0, end: 0 },
        up: { start: 0, end: 0 },
      },
    },
    "tilemap_packed",
  ],
  emotes: [
    { name: "exclamation", file: "emotes_kenney/emote_exclamation.png" },
    { name: "exclamations", file: "emotes_kenney/emote_exclamations.png" },
    { name: "question", file: "emotes_kenney/emote_question.png" },
    { name: "heart", file: "emotes_kenney/emote_heart.png" },
    { name: "stars", file: "emotes_kenney/emote_stars.png" },
    { name: "drop", file: "emotes_kenney/emote_drop.png" },
    { name: "music", file: "emotes_kenney/emote_music.png" },
    { name: "anger", file: "emotes_kenney/emote_anger.png" },
    { name: "dots", file: "emotes_kenney/emote_dots1.png" },
    { name: "sword1", file: "tiles_kenney/sword1.png" },
    { name: "sword2", file: "tiles_kenney/sword2.png" },
    { name: "sword3", file: "tiles_kenney/sword3.png" },
    { name: "sword4", file: "tiles_kenney/sword4.png" },
    { name: "dual_axes", file: "tiles_kenney/dual_axes.png" },
    { name: "axe", file: "tiles_kenney/axe.png" },
    { name: "hammer", file: "tiles_kenney/hammer.png" },
    { name: "attack", file: "tiles_kenney/tile_0060.png" },
    { name: "heart_full", file: "heart_kenney/heart_full.png" },
    { name: "heart_half", file: "heart_kenney/heart_half.png" },
    { name: "heart_empty", file: "heart_kenney/heart_empty.png" },
    { name: "impact0", file: "impact/0.png" },
    { name: "impact1", file: "impact/1.png" },
    { name: "impact2", file: "impact/2.png" },
    { name: "impact3", file: "impact/3.png" },
    { name: "impact4", file: "impact/4.png" },
    { name: "impact5", file: "impact/5.png" },
  ],
};
